# Building a Document-Term Matrix from scratch


In [6]:
# install & import the libraries needed
!pip3 install pandas
!pip3 install scikit-learn
from typing import List
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [191]:
# A mini corpus to play with
CORPUS = [
    'this is the first document',
    'this is the second document',
    'and this is the third document',
    'is this the first document ?'
]

In [192]:
def tf(term: str, doc: str) -> int:
    ### TODO 1 ### 
    # count the frequency of term in doc. hint: str.count()
    tf = doc.count(term)
    ##############
    return tf

In [193]:
def build_dtm(corpus: List[str]) -> pd.DataFrame:
    ### TODO 2 ###
    # build a vocabulary of the given corpus - use nested list comprehension, str.split(" "),  set,  and list
    word = []
    for i in range(len(CORPUS)) :
        CORPUS[i].split(" ")
        for j in range(len(CORPUS[i].split(" "))) :
            word.append(CORPUS[i].split(" ")[j])
    vocab: List[str] = [
        term
        for term in list(set(word))
    ]
    ##############

    ### TODO 3 ###
    # populate a dtm - get use of the tf function

    dtm: List[List[int]] = [
            [tf(voca,CORPUS[0])
            for voca in vocab],
            [tf(voca,CORPUS[1])
            for voca in vocab],
            [tf(voca,CORPUS[2])
            for voca in vocab],
            [tf(voca,CORPUS[3])
            for voca in vocab]
    ]

    ##############
    # return dtm as a pandas dataframe (for better visualization of the columns)
    dtm = pd.DataFrame(data=dtm, columns=vocab)
    return dtm

In [195]:
 # build a dtm from the corpus, and have a look at it
dtm = build_dtm(CORPUS)
print(dtm)

   this  second  ?  first  and  the  document  is  third
0     1       0  0      1    0    1         1   2      0
1     1       1  0      0    0    1         1   2      0
2     1       0  0      0    1    1         1   2      1
3     1       0  1      1    0    1         1   2      0


다음과 같은 결과가 나와야 합니다 (단어의 순서는 달라도 괜찮습니다):
```
   is  ?  first  and  document  this  the  second  third
0   2  0      1    0         1     1    1       0      0
1   2  0      0    0         1     1    1       1      0
2   2  0      0    1         1     1    1       0      1
3   2  1      1    0         1     1    1       0      0
```
(슬라이드에는 0또는 1로 카운트를 했지만, 튜토리얼에서는 그냥 카운트를 하겠습니다! (e.g. is가 두 개 포함되어 있다면 그냥 2로)

In [196]:
# this will print out the similarities of the documents to each other
sim_matrix = cosine_similarity(dtm.to_numpy(), dtm.to_numpy())
print(sim_matrix)

[[1.         0.875      0.82495791 0.94280904]
 [0.875      1.         0.82495791 0.82495791]
 [0.82495791 0.82495791 1.         0.77777778]
 [0.94280904 0.82495791 0.77777778 1.        ]]


다음과 같은 결과가 나와야 합니다:
```
[[1.         0.875      0.82495791 0.94280904]
 [0.875      1.         0.82495791 0.82495791]
 [0.82495791 0.82495791 1.         0.77777778]
 [0.94280904 0.82495791 0.77777778 1.        ]]
```

## **TODO 4**: 마지막으로, 다음의 질문에 답해주세요.
> 위 `sim_matrix`를 보고 `dtm`의 어떤 문제를 발견할 수 있나요? (힌트: `CORPUS`에 있는 문장의 의미는 모두 동일한가요?)

In [ ]:
#1,4 는 거의 일치하지만 한가지로 완전 다른의미.